// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBilke9Aau8Z-x50E3lLmvnjwEyltR0KbQ',
    appId: '1:1079029816717:web:0a638e356bf19dd77031c4',
    messagingSenderId: '1079029816717',
    projectId: 'pmsn2024b',
    authDomain: 'pmsn2024b.firebaseapp.com',
    storageBucket: 'pmsn2024b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPUZjcQBXYy2ocscUDG34dqRLiH_Put94',
    appId: '1:1079029816717:android:30fa600f4fd6c27d7031c4',
    messagingSenderId: '1079029816717',
    projectId: 'pmsn2024b',
    storageBucket: 'pmsn2024b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpuKFATVf5L-hoqutj3iqmcJDT8xkMWTQ',
    appId: '1:1079029816717:ios:c320f26c73f428387031c4',
    messagingSenderId: '1079029816717',
    projectId: 'pmsn2024b',
    storageBucket: 'pmsn2024b.appspot.com',
    iosBundleId: 'com.example.pmsn2024b',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpuKFATVf5L-hoqutj3iqmcJDT8xkMWTQ',
    appId: '1:1079029816717:ios:c320f26c73f428387031c4',
    messagingSenderId: '1079029816717',
    projectId: 'pmsn2024b',
    storageBucket: 'pmsn2024b.appspot.com',
    iosBundleId: 'com.example.pmsn2024b',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBilke9Aau8Z-x50E3lLmvnjwEyltR0KbQ',
    appId: '1:1079029816717:web:56fc036f5a0ea06f7031c4',
    messagingSenderId: '1079029816717',
    projectId: 'pmsn2024b',
    authDomain: 'pmsn2024b.firebaseapp.com',
    storageBucket: 'pmsn2024b.appspot.com',
  );

}